### ISSUE TITLE
Anybody tested this on Xiaomi Redmi Note 10S?

### ISSUE THREAD

**Issue by unfa** [ksalokya/xiaomi_debloater_script#1]
I am considering purchasing a Xiaomi phone, but I've heard they put a lot of crap in the factory OS.
I am running Linux on all of my hardware so I don't have access to Windows, that's why I was looking for something like this script.

Did anyone test it on Xiaomi Redmi Note 10S?

**Comment by ksalokya** [comment]
Well, it will work on any Android phone but the apps listed in the script predominantly found on Xiaomi phones. You can modify the script according to your need (which apps to keep/uninstall/disable).
By any means, if you ran into trouble you can factory reset your phone to undo all changes but make sure to back-up data.

**Comment by unfa** [comment]
Thank you. I need to look up how to backup all that so in case of a failure I can quickly get up and running again without losing everything.
