### ISSUE TITLE
Can't run the script on Linux - character encoding issue?

### ISSUE THREAD

**Issue by unfa** [ksalokya/xiaomi_debloater_script#2]
I wasn't able to run the script directly. Strange, I didn't see any problem in the .sh file code, but bash kept complaining:

```
$ ./debloater_for_linux.sh 
bash: ./debloater_for_linux.sh: /bin/bash^M: bad interpreter: No such file or directory
```

When I forced bash to interpret the file anyway (making the first hashbang line redundant) I got this:

```
$ bash ./debloater_for_linux.sh 
./debloater_for_linux2.sh: line 2: $'\r': command not found
./debloater_for_linux2.sh: line 3: syntax error near unexpected token `$'\r''
'/debloater_for_linux2.sh: line 3: `ascii_intro()
```

I suspect a problem with character encoding.

Can anyone confirm this?

I am using Manjaro KDE, and got the files by cloning the repository with `git`.

**Comment by ksalokya** [comment]
I hope so you have given executable permission to the script file, if so there are some troubleshooting options available here. [Link](https://stackoverflow.com/questions/14219092/bash-script-and-bin-bashm-bad-interpreter-no-such-file-or-directory) . Try it and let me know.

**Comment by ksalokya** [comment]
If troubleshooting also fails, just remove those asci arts and input stuffs and copy those commands (starting with ./adb for uninstall or disable) in separate files, grant executable permission and try it out!
